# Generated by Django 6.1.1 on 2026-09-29 22:22

from django.db import migrations

import apps.user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profilemodel',
            managers=[
                ('objects', apps.user.managers.UserManager()),
            ],
        ),
    ]
