# Generated by Django 6.1.1 on 2026-09-29 22:23

from django.db import migrations

import apps.user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profilemodel_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profilemodel',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', apps.user.managers.UserManager()),
            ],
        ),
    ]
