# Generated by Django 6.1.1 on 2026-09-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('avail_status', models.BooleanField()),
                ('cpu', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'computers',
            },
        ),
    ]
