# Generated by Django 6.1.1 on 2026-09-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computermodel',
            name='ram',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
    ]
