# Generated by Django 6.1.1 on 2026-09-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_computermodel_created_at_computermodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='computermodel',
            name='price',
            field=models.IntegerField(default=60000),
            preserve_default=False,
        ),
    ]
