# Generated by Django 6.1.1 on 2026-09-10 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0004_computermodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='avail_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='ram',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)]),
        ),
    ]
