# Generated by Django 6.1.1 on 2026-09-14 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_shops', '0001_initial'),
        ('computers', '0005_alter_computermodel_avail_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computermodel',
            name='computer_shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='computer_shops.computershopmodel'),
            preserve_default=False,
        ),
    ]
