# Generated by Django 6.1.1 on 2026-09-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_shops', '0001_initial'),
        ('computers', '0006_computermodel_computer_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='computer_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='computer_shops.computershopmodel'),
        ),
    ]
