# Generated by Django 6.1.1 on 2026-09-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0007_alter_computermodel_computer_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computermodel',
            name='ram',
        ),
        migrations.AddField(
            model_name='computermodel',
            name='ram_type',
            field=models.CharField(choices=[('DDR3', 'Ddr3'), ('DDR4', 'Ddr4'), ('DDR5', 'Ddr5')], default='DDR5', max_length=4),
            preserve_default=False,
        ),
    ]
