# Generated by Django 6.1.1 on 2026-09-19 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0008_remove_computermodel_ram_computermodel_ram_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='cpu',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(Intel Core|AMD Ryzen|Apple Silicon) ([A-Z][0-9]+|[0-9]+|[0-9]+ [0-9]+|[A-Z][0-9]+ [A-Z][a-z]+)$', 'CPU field must consist Intel Core/AMD Ryzen/Apple Silicon + valid model name')]),
        ),
    ]
