# Generated by Django 6.1.1 on 2026-09-19 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0009_alter_computermodel_cpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='computermodel',
            name='ram',
            field=models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(4)]),
            preserve_default=False,
        ),
    ]
