# Generated by Django 6.1.1 on 2026-09-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0010_computermodel_ram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computermodel',
            options={'ordering': ('id',)},
        ),
    ]
