# Generated by Django 6.1.1 on 2026-09-19 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0011_alter_computermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='brand',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z]', 'Brand/model name must start with a capital!')]),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='model',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z]', 'Brand/model name must start with a capital!')]),
        ),
    ]
