# Generated by Django 6.1.1 on 2026-09-23 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0012_alter_computermodel_brand_alter_computermodel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='brand',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z]', 'Brand/model name must start with a capital!')]),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='price',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='ram',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='year',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2027)]),
        ),
    ]
